version: '3.1'

services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8081:8080
